
gpus_per_node: 8

nnodes: 1

node_rank: 0

master_addr: localhost

master_port: 6000

backend: nccl

norm_epsilon: 1.0e_6

training_phase: pretrain

seq_length: 1024

max_position_embeddings: 4096

init_method_std: 0.02

micro_batch_size: 1

global_batch_size: 512

lr: 0.0002

min_lr: 1.0e_5

clip_grad: 1.0

weight_decay: 0.01

optimizer: adam

adam_beta1: 0.9

adam_beta2: 0.95

adam_eps: 1.0e_5

train_iters: 50000

lr_decay_iters: 50000

lr_decay_style: cosine

lr_warmup_fraction: 0.002

initial_loss_scale: 65536

bf16: true

load:

save:

save_interval: 10000000

ckpt_format: torch

dataloader_save:

attention_backend: flash

pipeline_model_parallel_size: 1

tensor_model_parallel_size: 1

use_distributed_optimizer: true

overlap_grad_reduce: true

overlap_param_gather: true

distributed_backend: nccl

log_interval: 1

tensorboard_dir:

log_timers_to_tensorboard: true