_target_: loongforge.models.diffusion.QwenImageConfig
model_type: "qwen_image"
num_layers: 60
hidden_size: 3072
ffn_hidden_size: 12288
num_attention_heads: 24
num_query_groups: 24
kv_channels: 128
text_dim: 3584
latent_channels: 16
latent_in_channels: 16
latent_out_channels: 16
latent_patch_size: [1, 2, 2]
latent_space_scale: 0.5
latent_time_scale: 1.0
num_latent_frames: 1
max_latent_height: 1024
max_latent_width: 1024
patch_size: 2
patch_dim: 64
time_dim: 256
axes_dim: [16, 56, 56]
rope_theta: 10000
scale_rope: true
use_layer3d_rope: false
use_additional_t_cond: false
qwen_image_zero_cond_t: true
norm_epsilon: 1e-6
normalization: "LayerNorm"
position_embedding_type: "rope"
add_position_embedding: false
rotary_interleaved: false
swiglu: false
attention_dropout: 0.0
hidden_dropout: 0.0
add_bias_linear: true
add_qkv_bias: true
qk_layernorm: false
untie_embeddings_and_output_weights: true
attention_softmax_in_fp32: true
