ARG BASE_IMAGE="nvcr.io/nvidia/pytorch:25.06-py3"
FROM ${BASE_IMAGE}

ARG COMPILE_ENV={{COMPILE_ENV}}

ARG INSTALL_TransformerEngine_FLAG="true"

ARG INSTALL_LEROBOT="false"

RUN mkdir -p /workspace 
COPY ./OmniTraining /workspace/OmniTraining
RUN bash /workspace/OmniTraining/docker/install_opensource.sh ${COMPILE_ENV} \
    ${INSTALL_TransformerEngine_FLAG} ${INSTALL_LEROBOT}