// Auto-generated by scripts/extract_cuda_kernels.py
// This file registers CUDA kernel bindings via pybind11.
//
// Kernel .cu files are compiled separately so ninja can parallelize builds.

#include <cstddef>
#include <cstdint>
#include <torch/extension.h>

namespace wallx_cuda_get_rope_index {
void GetRopeIndex(const c10::optional<at::Tensor>& input_ids, const c10::optional<at::Tensor>& image_grid_thw, const c10::optional<at::Tensor>& video_grid_thw, const c10::optional<at::Tensor>& second_per_grid_ts, const c10::optional<at::Tensor>& attention_mask, const at::Tensor& position_ids, const at::Tensor& mrope_deltas, const at::Tensor& workspace, int spatial_merge_size, int image_token_id, int video_token_id, int vision_start_token_id, float tokens_per_second);
int64_t GetRopeIndexGetWorkSpace(const c10::optional<at::Tensor>& input_ids, const c10::optional<at::Tensor>& image_grid_thw, const c10::optional<at::Tensor>& video_grid_thw);
}  // namespace wallx_cuda_get_rope_index

namespace wallx_cuda_m_rope {
void MRope(const at::Tensor& q, const at::Tensor& k, const at::Tensor& q_embed, const at::Tensor& k_embed, const at::Tensor& cos, const at::Tensor& sin, const int first, const int second );
void MRopeInplace(const at::Tensor& q, const at::Tensor& k, const at::Tensor& cos, const at::Tensor& sin, const int first, const int second );
void MRopeInplacePack(const at::Tensor& qkv, const at::Tensor& cos, const at::Tensor& sin, int64_t q_num_heads, int64_t kv_num_heads, const int first, const int second);
void MRopeInplacePackBackward(const at::Tensor& dqkv, const at::Tensor& cos, const at::Tensor& sin, int64_t q_num_heads, int64_t kv_num_heads, const int first, const int second);
void MRopeBackward( const at::Tensor& grad_q_embed, const at::Tensor& grad_k_embed, const at::Tensor& grad_q, const at::Tensor& grad_k, const at::Tensor& cos, const at::Tensor& sin, const int first, const int second );
}  // namespace wallx_cuda_m_rope

namespace wallx_cuda_permute {
void MoePermuteTopKOp( const at::Tensor& input, const at::Tensor& indices, const at::Tensor& sorted_indices, const at::Tensor& row_id, const at::Tensor& sorted_row_id, const at::Tensor& temp_storage, const at::Tensor& permuted_output, const at::Tensor& row_id_map, int64_t num_out_tokens, int64_t max_expanded_token_num );
void MoeRecoverTopKOp( const at::Tensor& input, const at::Tensor& row_id_map, const c10::optional<at::Tensor>& prob, const at::Tensor& unpermuted_output, int64_t num_tokens, int64_t num_topK );
void MoeRecoverTopKBwdOp( const at::Tensor& input_bwd, const at::Tensor& input_fwd, const at::Tensor& row_id_map, const at::Tensor& prob, const at::Tensor& act_grad, const at::Tensor& prob_grad );
size_t CubSortPairGetStorageBytes(int64_t num_items);
}  // namespace wallx_cuda_permute

namespace wallx_cuda_rope {
void Rope(const at::Tensor& q, const at::Tensor& k, const at::Tensor& q_embed, const at::Tensor& k_embed, const at::Tensor& cos, const at::Tensor& sin, bool interleave );
void RopeInplace(const at::Tensor& q, const at::Tensor& k, const at::Tensor& cos, const at::Tensor& sin, bool interleave );
void RopeInplacePack(const at::Tensor& qkv, const at::Tensor& cos, const at::Tensor& sin, int64_t q_num_heads, int64_t kv_num_heads, bool interleave);
void RopeInplacePackBackward(const at::Tensor& dqkv, const at::Tensor& cos, const at::Tensor& sin, int64_t q_num_heads, int64_t kv_num_heads, bool interleave);
void RopeBackward( const at::Tensor& grad_q_embed, const at::Tensor& grad_k_embed, const at::Tensor& grad_q, const at::Tensor& grad_k, const at::Tensor& cos, const at::Tensor& sin, bool interleave );
}  // namespace wallx_cuda_rope

namespace wallx_cuda_rot_pos {
void GetTokenCounts( const at::Tensor& grid_thw, const at::Tensor& token_counts, int spatial_merge_size );
void RotPosEmb( const at::Tensor& inv_freq, const at::Tensor& grid_thw, const at::Tensor& output, const at::Tensor& cumsum_tokens, int spatial_merge_size );
}  // namespace wallx_cuda_rot_pos

namespace wallx_cuda_window_index {
void GetWindowIndex( const at::Tensor& grid_thw, const at::Tensor& grid_info_tensor, const at::Tensor& window_indices, const at::Tensor& cu_window_seqlens, const at::Tensor& window_counts_tensor, int max_grid_t, int spatial_merge_size, int vit_merger_window_size, int patch_size, int spatial_merge_unit);
void GetTotals( const at::Tensor& grid_thw, const at::Tensor& grid_info_tensor, const at::Tensor& global_totals_tensor, int spatial_merge_size, int vit_merger_window_size );
}  // namespace wallx_cuda_window_index

PYBIND11_MODULE(TORCH_EXTENSION_NAME, m) {
    m.def("rope", &wallx_cuda_rope::Rope);
    m.def("rope_inplace", &wallx_cuda_rope::RopeInplace);
    m.def("rope_inplace_pack", &wallx_cuda_rope::RopeInplacePack);
    m.def("rope_inplace_pack_bwd", &wallx_cuda_rope::RopeInplacePackBackward);
    m.def("rope_bwd", &wallx_cuda_rope::RopeBackward);
    m.def("m_rope", &wallx_cuda_m_rope::MRope);
    m.def("m_rope_inplace", &wallx_cuda_m_rope::MRopeInplace);
    m.def("m_rope_inplace_pack", &wallx_cuda_m_rope::MRopeInplacePack);
    m.def("m_rope_inplace_pack_bwd", &wallx_cuda_m_rope::MRopeInplacePackBackward);
    m.def("m_rope_bwd", &wallx_cuda_m_rope::MRopeBackward);
    m.def("get_token_counts", &wallx_cuda_rot_pos::GetTokenCounts);
    m.def("rot_pos", &wallx_cuda_rot_pos::RotPosEmb);
    m.def("get_rope_index", &wallx_cuda_get_rope_index::GetRopeIndex);
    m.def("get_rope_index_getworkspace", &wallx_cuda_get_rope_index::GetRopeIndexGetWorkSpace);
    m.def("get_window_index", &wallx_cuda_window_index::GetWindowIndex);
    m.def("get_totals", &wallx_cuda_window_index::GetTotals);
    m.def("permute", &wallx_cuda_permute::MoePermuteTopKOp);
    m.def("unpermute", &wallx_cuda_permute::MoeRecoverTopKOp);
    m.def("unpermute_bwd", &wallx_cuda_permute::MoeRecoverTopKBwdOp);
    m.def("cub_sort_pair_get_storage_bytes", &wallx_cuda_permute::CubSortPairGetStorageBytes);
    // NOTE: the bitwise-exact swiglu/rmsnorm kernels are deliberately NOT bound here.
    // This module is built with --use_fast_math, which would substitute the
    // approximate __expf and enable ftz, breaking their bitwise match with eager.
    // They live in binding_exact.cu -> _cuda_ext_exact_bin (strict math flags).
}
