
_target_: aiak_training_omni.models.encoder.MLPAdapterConfig

normalization: "RMSNorm"
add_bias_linear: True
model_type: "qwen2_5_vl_adapter"

convert_file: "configs/models/image_projector/ckpt_convert/qwen_mlp_adapter_convert.yaml"