num_layers: null
hidden_size: null
ffn_hidden_size: null
num_attention_heads: null
num_experts: null
moe_ffn_hidden_size: null
moe_shared_expert_intermediate_size: null
q_lora_rank: null
kv_lora_rank: null
qk_head_dim: null
qk_pos_emb_head_dim: null
v_head_dim: null
moe_layer_freq: null
position_embedding_type: "rope"
add_position_embedding: false
rotary_interleaved: false
normalization: "RMSNorm"
swiglu: true
attention_dropout: 0.0
hidden_dropout: 0.0
add_bias_linear: false
add_qkv_bias: false
qk_layernorm: false
untie_embeddings_and_output_weights: true
vocab_size_in_config_file: null
num_query_groups: null
apply_rope_fusion: true
multi_latent_attention: true