#!/usr/bin/env bash
# Copyright 2026 The LoongForge Authors.
# SPDX-License-Identifier: Apache-2.0
#
# DreamZero LoRA fine-tuning with the Wan2.2-TI2V-5B backbone using
# 8-GPU FSDP by default.
#
# Usage:
#   bash examples/embodied/dreamzero/run_dreamzero_wan22_5b_lora_finetune.sh
#   DROID_DATA_ROOT=/path/to/droid_lerobot \
#     WAN22_CKPT_DIR=/path/to/Wan2.2-TI2V-5B \
#     WAN21_CKPT_DIR=/path/to/Wan2.1-I2V-14B-480P \
#     bash examples/embodied/dreamzero/run_dreamzero_wan22_5b_lora_finetune.sh
#
# Optional offline feature cache generated by precompute_dreamzero_cache.sh:
#   CACHE_DIR=/path/to/dreamzero_cache \
#     bash examples/embodied/dreamzero/run_dreamzero_wan22_5b_lora_finetune.sh
# CACHE_MANIFEST defaults to $CACHE_DIR/manifest.json. If the cache was
# generated with a non-default SAMPLE_TRANSFORM_SEED, pass the same value here.

set -euo pipefail

# ── Paths and model ────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"

export LOONGFORGE_PATH=${LOONGFORGE_PATH:-"$PROJECT_ROOT"}

DREAMZERO_DATA_ROOT=${DREAMZERO_DATA_ROOT:-"/workspace/dreamzero/data"}
DREAMZERO_CKPT_ROOT=${DREAMZERO_CKPT_ROOT:-"/workspace/dreamzero/checkpoints"}

MODEL_NAME=${MODEL_NAME:-dreamzero_lora_wan22_5b}
DATA_PATH=${DATA_PATH:-"${DROID_DATA_ROOT:-$DREAMZERO_DATA_ROOT/droid_lerobot}"}
OUTPUT_DIR=${OUTPUT_DIR:-"/workspace/outputs/dreamzero/droid_wan22_5b_lora"}
TENSORBOARD_DIR=${TENSORBOARD_DIR:-"/workspace/tensorboard-log/dreamzero/droid_wan22_5b_lora"}

export WAN21_CKPT_DIR=${WAN21_CKPT_DIR:-"$DREAMZERO_CKPT_ROOT/Wan2.1-I2V-14B-480P"}
export WAN22_CKPT_DIR=${WAN22_CKPT_DIR:-"$DREAMZERO_CKPT_ROOT/Wan2.2-TI2V-5B"}
TOKENIZER_PATH=${TOKENIZER_PATH:-"$WAN22_CKPT_DIR/google/umt5-xxl"}

# ── Data behavior ─────────────────────────────
# Exclude samples that cannot provide a complete language-conditioned chunk.
REQUIRE_FULL_LANGUAGE_CHUNKS=${REQUIRE_FULL_LANGUAGE_CHUNKS:-false}

# ── Activation checkpointing ───────────────────────
# An empty module-pattern value disables activation checkpointing. Skip modules
# are exact qualified module keys excluded from the selected pattern.
ACTIVATION_CHECKPOINT_MODULE_PATTERNS=${ACTIVATION_CHECKPOINT_MODULE_PATTERNS-"action_head.model.blocks.*"}
ACTIVATION_CHECKPOINT_SKIP_MODULES=${ACTIVATION_CHECKPOINT_SKIP_MODULES-"action_head.model.blocks.3,action_head.model.blocks.29"}
ACTIVATION_CHECKPOINT_ARGS=()
if [[ -n "$ACTIVATION_CHECKPOINT_MODULE_PATTERNS" ]]; then
    ACTIVATION_CHECKPOINT_ARGS=(
        --activation-checkpoint-module-patterns "$ACTIVATION_CHECKPOINT_MODULE_PATTERNS"
    )
fi
if [[ -n "$ACTIVATION_CHECKPOINT_SKIP_MODULES" ]]; then
    ACTIVATION_CHECKPOINT_ARGS+=(
        --activation-checkpoint-skip-modules "$ACTIVATION_CHECKPOINT_SKIP_MODULES"
    )
fi

# ── Feature cache ─────────────────────────────
CACHE_ARGS=()
CACHE_DESCRIPTION="disabled (online features)"
CACHE_DIR=${CACHE_DIR:-}
CACHE_MANIFEST=${CACHE_MANIFEST:-}
# Must match the transform seed recorded in the cache manifest.
SAMPLE_TRANSFORM_SEED=${SAMPLE_TRANSFORM_SEED:-0}
if [[ -n "$CACHE_DIR" ]]; then
    CACHE_MANIFEST=${CACHE_MANIFEST:-"$CACHE_DIR/manifest.json"}
    if [[ ! -f "$CACHE_MANIFEST" ]]; then
        echo "DreamZero cache manifest not found: $CACHE_MANIFEST" >&2
        exit 2
    fi
    CACHE_ARGS=(
        model.precomputed_cache.enabled=true
        model.precomputed_cache.cache_dir="$CACHE_DIR"
        model.precomputed_cache.manifest="$CACHE_MANIFEST"
        model.precomputed_cache.strict=true
        model.precomputed_cache.validation.validate_artifact=true
        model.precomputed_cache.validation.require_success=true
        data.use_sample_transform_seed=true
        data.sample_transform_seed="$SAMPLE_TRANSFORM_SEED"
    )
    CACHE_DESCRIPTION="$CACHE_DIR"
fi

# ── Distributed and batch sizing ────────────────────
GPUS_PER_NODE=${GPUS_PER_NODE:-${NUM_GPUS:-8}}
NNODES=${NNODES:-${WORLD_SIZE:-1}}
NODE_RANK=${NODE_RANK:-${RANK:-0}}
MASTER_ADDR=${MASTER_ADDR:-localhost}
MASTER_PORT=${MASTER_PORT:-6000}

PER_DEVICE_BATCH_SIZE=${PER_DEVICE_BATCH_SIZE:-1}
GLOBAL_BATCH_SIZE=${GLOBAL_BATCH_SIZE:-$((GPUS_PER_NODE * NNODES * PER_DEVICE_BATCH_SIZE))}
LOCAL_BATCH_SIZE=$((GPUS_PER_NODE * NNODES * PER_DEVICE_BATCH_SIZE))
if (( GLOBAL_BATCH_SIZE % LOCAL_BATCH_SIZE != 0 )); then
    echo "GLOBAL_BATCH_SIZE must be divisible by GPUS_PER_NODE * NNODES * PER_DEVICE_BATCH_SIZE" >&2
    exit 2
fi
GRADIENT_ACCUMULATION_STEPS=${GRADIENT_ACCUMULATION_STEPS:-$((GLOBAL_BATCH_SIZE / LOCAL_BATCH_SIZE))}

# ── Training schedule ──────────────────────────
TRAIN_ITERS=${TRAIN_ITERS:-100}
LR_WARMUP_ITERS=${LR_WARMUP_ITERS:-$(((TRAIN_ITERS + 19) / 20))}

# ── Launch ──────────────────────────────────
DISTRIBUTED_ARGS=(
    --nproc_per_node "$GPUS_PER_NODE"
    --nnodes "$NNODES"
    --node_rank "$NODE_RANK"
    --master_addr "$MASTER_ADDR"
    --master_port "$MASTER_PORT"
)

CMD=(
    torchrun "${DISTRIBUTED_ARGS[@]}"
    "$LOONGFORGE_PATH/loongforge/embodied/train.py"
    --model-name "$MODEL_NAME"
    --dataset-format lerobot_datasets
    --dataset-strategy dreamzero
    --dataset-path "$DATA_PATH"
    --tokenizer-path "$TOKENIZER_PATH"
    --video-backend decord
    --num-workers "${NUM_WORKERS:-4}"
    --trainer-type FinetuneTrainer
    --use-lora
    --lora-r "${LORA_R:-4}"
    --lora-alpha "${LORA_ALPHA:-4}"
    --lora-dropout "${LORA_DROPOUT:-0.0}"
    --lora-init "${LORA_INIT:-true}"
    --train-iters "$TRAIN_ITERS"
    --per-device-batch-size "$PER_DEVICE_BATCH_SIZE"
    --gradient-accumulation-steps "$GRADIENT_ACCUMULATION_STEPS"
    --seed 42
    --output-dir "$OUTPUT_DIR"
    --lr-base "${LR:-1.0e-5}"
    --min-lr 0
    --lr-decay-style cosine_with_min_lr
    --lr-warmup-iters "$LR_WARMUP_ITERS"
    --optimizer AdamW
    --clip-grad 1.0
    --weight-decay 1.0e-5
    --weight-decay-grouping bias_norm
    --adam-beta1 0.95
    --adam-beta2 0.999
    --adam-eps 1.0e-8
    --save-interval "${SAVE_INTERVAL:-$TRAIN_ITERS}"
    --save-format dcp
    --distributed-strategy fsdp
    --dtype bfloat16
    --fsdp-original-param-dtype fp32
    --fsdp-reduce-dtype bf16
    --fsdp-cast-forward-inputs
    --fsdp-wrap-modules "WanTextEncoder,VisionTransformer,CausalWanAttentionBlock"
    --fsdp-forward-prefetch-distance 1
    --fsdp-backward-prefetch-distance 1
    "${ACTIVATION_CHECKPOINT_ARGS[@]}"
    --log-interval "${LOG_INTERVAL:-1}"
    --tensorboard-dir "$TENSORBOARD_DIR"
    --wandb-mode "${WANDB_MODE:-disabled}"
    --wandb-project "${WANDB_PROJECT:-dreamzero}"
    "${CACHE_ARGS[@]}"
    "$@"
    model.skip_init_weights=false
    data.require_full_language_chunks="$REQUIRE_FULL_LANGUAGE_CHUNKS"
)

echo "========================================================================"
echo "  LoongForge DreamZero Wan2.2-5B LoRA Fine-Tuning"
echo "  GPUs:       $GPUS_PER_NODE x $NNODES nodes"
echo "  Data:       $DATA_PATH"
echo "  Wan2.2:     $WAN22_CKPT_DIR"
echo "  Wan2.1:     $WAN21_CKPT_DIR"
echo "  Cache:      $CACHE_DESCRIPTION"
echo "  Output:     $OUTPUT_DIR"
echo "========================================================================"

PYTHONPATH="$LOONGFORGE_PATH:${PYTHONPATH:-}" "${CMD[@]}"
